# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.3"

gem "activerecord", ">= 7.0.4.1"
gem 'allure-cucumber'
gem 'appium_lib'
gem 'benchmark'
gem 'capybara'
gem 'cpf_cnpj'
gem 'cucumber'
gem 'cucumber-rails'
gem 'faker', '>= 2.22'
gem 'ffi',  '>= 1.1'
gem 'fiddle'
gem 'fileutils'
gem 'nif', '>= 0.0.3'
gem "rack", ">= 2.2.6.4"
gem 'rails'
gem 'rspec'
gem 'sys-uname'
gem 'selenium-webdriver'
gem 'watir-scroll'
gem 'webdrivers', '>= 5.0'
gem 'json'

group :development do
  gem 'readapt'
  gem 'better_errors'
  gem 'binding_of_caller'
end
